name: .NET Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Setup .NET SDK
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'  # Adjust according to your .NET version

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build the project
      run: dotnet build --configuration Release

    # Run tests and collect code coverage
    - name: Run tests with coverage
      run: |
        dotnet test --configuration Release --collect:"XPlat Code Coverage"

    # List the files in the TestResults directory (for debugging)
    - name: List files in TestResults
      run: ls -R ./TestResults

    # Upload test results as artifacts
    - name: Upload test results and coverage
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          ./TestResults/**/*.trx
          ./TestResults/**/*.cobertura.xml  # If you want to upload coverage report
